# Generated by Django 3.2.5 on 2021-08-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_a', models.IntegerField(default=0)),
                ('auto_c', models.IntegerField(default=0)),
                ('tele_a', models.IntegerField(default=0)),
                ('tele_c', models.IntegerField(default=0)),
                ('end_c', models.IntegerField(default=0)),
                ('foul', models.IntegerField(default=0)),
                ('tech', models.IntegerField(default=0)),
                ('all_point', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.match')),
            ],
        ),
        migrations.CreateModel(
            name='Each',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.BooleanField(default=False)),
                ('auto_end', models.BooleanField(default=False)),
                ('tele_end', models.BooleanField(default=False)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.score')),
            ],
        ),
    ]
