# Generated by Django 3.2.5 on 2021-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='rank_point',
            field=models.IntegerField(default=0),
        ),
    ]
