# Generated by Django 3.2.5 on 2021-08-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('team', models.TextField(blank=True, default='')),
                ('serial', models.IntegerField()),
                ('rankBlue', models.IntegerField(default=0)),
                ('rankRed', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.event')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.matchtype')),
            ],
            options={
                'ordering': ['event_id', 'type', 'serial'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(to='index.Team'),
        ),
    ]
